language: node_js
sudo: false
node_js:
  - 10
  - 9
  - 8
  - 7
  - 6
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
  # - export CHROME_BIN=chromium-browser
  # - export DISPLAY=:99.0
  # - sh -e /etc/init.d/xvfb start
before_script:
  - wget http://chromedriver.storage.googleapis.com/2.10/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/virtualenv/python2.7.9/
  - export CHROME_BIN=chromium-browser
  - "export DISPLAY=:99.0"
  # - "sh -e /etc/init.d/xvfb start"
  - sleep 3 
  # - npm install karma-sauce-launcher
  # - export DISPLAY=:99.0
  # - sh -e /etc/init.d/xvfb start
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
install:
  - npm install
script:
  - npm run test-karma

after_success:
- bash <(curl -s https://codecov.io/bash)
env:
  global:
  - CODECOV_TOKEN: 31102f8c-91a5-4809-a163-1fbb702e7204