language: node_js
sudo: false
node_js:
  - 10
  - 9
  - 8
  - 7
  - 6
matrix:
  include:
    - node_js: "4.0"
      env: BROWSER=true
# branches:
#   only:
#   - master
cache:
  directories:
  - node_modules
before_install:
  - npm install -g npm@2.6
  - npm install -g karma-cli
before_script:
  - npm install karma-sauce-launcher
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  - npm run test
  - "[ $BROWSER == false ] || npm run test-karma"
  - "[ $BROWSER == false ] || karma start karma.conf-sauce.js"
env:
  global:
  - CODECOV_TOKEN: 31102f8c-91a5-4809-a163-1fbb702e7204
  # matrix: BROWSER=false
after_success:
- npm run coveralls
- bash <(curl -s https://codecov.io/bash)